# Generated by Django 5.1.6 on 2025-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oil_req_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_name', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=50)),
                ('oil_type', models.CharField(max_length=20)),
                ('oil_amount', models.FloatField()),
                ('oil_per_amount', models.FloatField()),
                ('sup_oil_name', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('emp_money', models.IntegerField()),
            ],
        ),
    ]
